### ISSUE TITLE
Create AWS layer for WeasyPrint with the right pango version

### ISSUE THREAD

**Issue by apalencia77** [kotify/cloud-print-utils#12]
Any work in progress to generate a AWS layer for WeasyPrint >=57.2 that contain a Pango version >=1.44?

We are working in a project to generate complex PDF based on a HTML template. Our initial local tests are working properly using the WeasyPrint version 57.2.

After deploying the changes on the lambda function using the version 52.5, the PDF generated is different from the local ones.

We need @face-font support along with some new features included in the recent versions.

Thanks in advance.

**Comment by kalekseev** [comment]
Updated layer for latest WeasyPrint won't be released until AWS release lambda runtime with Pango >= 1.44 https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

See also https://github.com/kotify/cloud-print-utils/pull/11

**Comment by apalencia77** [comment]
@kalekseev Thanks for your response.

You mentioned as a workaround you can pack and run your lambda function as a docker container.

I've made several attempts to generate a lambda function based of the right docker image.

Can you help me to check the files in order to generate the docker container with a Pango version >=1.44?

Below the files used to generate the docker container:

**requirements.txt**
Jinja2==3.1.2
weasyprint==57.2

**Dockerfile**
#FROM public.ecr.aws/lambda/python:3.8
#FROM amazon/aws-lambda-python:3.8
FROM lambci/lambda:build-python3.8

COPY Roboto-Regular.ttf .
COPY Roboto-Bold.ttf .
COPY Roboto-Italic.ttf .
COPY Roboto-Light.ttf .
COPY requirements_html.txt .
COPY summary_report_template.html .
COPY summary_report.css .
COPY report_generator_from_html.py .
COPY common_library.py .

RUN yumdownloader --resolve \
    expat \
    glib2 \
    libffi \
    libffi-devel \
    cairo \
    pango && \
    rpmdev-extract *rpm

RUN ln libgobject-2.0.so.0 libgobject-2.0.so && \
    ln libcairo.so.2 libcairo.so && \
    ln libpango-1.0.so.0 pango-1.0 && \
    ln libpangoft2-1.0.so.0 pangoft2-1.0 && \
    ln libpangocairo-1.0.so.0 pangocairo-1.0

# RUN yum install -y libxml2 libxml2-devel libxslt libxslt-devel \
#     && pip3 install -r requirements_html.txt -t /var/task

COPY Roboto-Regular.ttf /var/task/
COPY Roboto-Bold.ttf /var/task/
COPY Roboto-Italic.ttf /var/task/
COPY Roboto-Light.ttf /var/task/
COPY requirements_html.txt /var/task/
COPY summary_report_template.html /var/task/
COPY summary_report.css /var/task/
COPY report_generator_from_html.py /var/task/
COPY common_library.py /var/task/

RUN pip install --upgrade pip &&\
    pip install -r requirements_html.txt

CMD [ "report_generator_from_html.lambda_handler"]

Thanks in advance.

**Comment by kalekseev** [comment]
@apalencia77 you can find instruction here https://aws.amazon.com/ru/blogs/aws/new-for-aws-lambda-container-image-support/ see "Building a Custom Image for Python"

I can add dockerfile to this project if someone ready to sponsor it.
