### ISSUE TITLE
AWS layer with latest weasyprint

### ISSUE THREAD

**Issue by inspiran** [kotify/cloud-print-utils#19]
It seems with the Python 3.12 runtime environment on lambda we finally have a recent version of Pango.

https://aws.amazon.com/blogs/compute/python-3-12-runtime-now-available-in-aws-lambda/

https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-AL2023.3.html

Maybe there is finally an opportunity to upgrade the layer?

**Comment by kalekseev** [comment]
@inspiran can you test #20 on aws lambda?

**Comment by inspiran** [comment]
oh my god, this is just brilliant, the layer works !  Thank you very much for your work!

**Comment by kalekseev** [comment]
The new layer with latest weasyprint was release a month ago.
