### ISSUE TITLE
Please Help Weasyprint + AWS Lambda + Python3.8: ERROR Executing

### ISSUE THREAD

**Issue by jjpretelta** [kotify/cloud-print-utils#2]
Regards @kalekseev ,

I'm just executing make `build/weasyprint-layer-python3.8.zip` to build the layer and git de zip file in the cloud-print-utils/build folder, but I'm getting this all the output:

docker run --rm \
    -v `pwd`/fonts:/out \
    -t lambci/lambda:build-python3.8 \
    bash /out/layer_builder.sh
: invalid optioner.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
Loaded plugins: ovl, priorities
amzn2-core                                                                                                    | 3.7 kB  00:00:00
amzn2extra-docker                                                                                             | 3.0 kB  00:00:00
(1/5): amzn2-core/2/x86_64/group_gz                                                                           | 2.5 kB  00:00:00
(2/5): amzn2extra-docker/2/x86_64/updateinfo                                                                  |   76 B  00:00:00
(3/5): amzn2extra-docker/2/x86_64/primary_db                                                                  |  68 kB  00:00:01
(4/5): amzn2-core/2/x86_64/updateinfo                                                                         | 259 kB  00:00:02
(5/5): amzn2-core/2/x86_64/primary_db                                                                         |  45 MB  00:02:57
 available.rpmdevtools
Resolving Dependencies
--> Running transaction check
---> Package yum-utils.noarch 0:1.1.31-46.amzn2.0.1 will be installed
--> Processing Dependency: python-kitchen for package: yum-utils-1.1.31-46.amzn2.0.1.noarch
--> Processing Dependency: libxml2-python for package: yum-utils-1.1.31-46.amzn2.0.1.noarch
--> Running transaction check
---> Package libxml2-python.x86_64 0:2.9.1-6.amzn2.4.1 will be installed
---> Package python-kitchen.noarch 0:1.1.1-5.amzn2 will be installed
--> Processing Dependency: python-chardet for package: python-kitchen-1.1.1-5.amzn2.noarch
--> Running transaction check
---> Package python-chardet.noarch 0:2.2.1-1.amzn2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================
 Package                          Arch                     Version                                Repository                    Size
=====================================================================================================================================
Installing:
 yum-utils                        noarch                   1.1.31-46.amzn2.0.1                    amzn2-core                   120 k
Installing for dependencies:
 libxml2-python                   x86_64                   2.9.1-6.amzn2.4.1                      amzn2-core                   245 k
 python-chardet                   noarch                   2.2.1-1.amzn2                          amzn2-core                   227 k
 python-kitchen                   noarch                   1.1.1-5.amzn2                          amzn2-core                   266 k

Transaction Summary
=====================================================================================================================================
Install  1 Package (+3 Dependent packages)

Total download size: 858 k
Installed size: 4.2 M
Downloading packages:
(1/4): libxml2-python-2.9.1-6.amzn2.4.1.x86_64.rpm                                                            | 245 kB  00:00:01
(2/4): python-chardet-2.2.1-1.amzn2.noarch.rpm                                                                | 227 kB  00:00:01
(3/4): yum-utils-1.1.31-46.amzn2.0.1.noarch.rpm                                                               | 120 kB  00:00:00
(4/4): python-kitchen-1.1.1-5.amzn2.noarch.rpm                                                                | 266 kB  00:00:00
-------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                403 kB/s | 858 kB  00:00:02
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-chardet-2.2.1-1.amzn2.noarch                                                                               1/4
  Installing : python-kitchen-1.1.1-5.amzn2.noarch                                                                               2/4
  Installing : libxml2-python-2.9.1-6.amzn2.4.1.x86_64                                                                           3/4
  Installing : yum-utils-1.1.31-46.amzn2.0.1.noarch                                                                              4/4
  Verifying  : yum-utils-1.1.31-46.amzn2.0.1.noarch                                                                              1/4
  Verifying  : libxml2-python-2.9.1-6.amzn2.4.1.x86_64                                                                           2/4
  Verifying  : python-kitchen-1.1.1-5.amzn2.noarch                                                                               3/4
  Verifying  : python-chardet-2.2.1-1.amzn2.noarch                                                                               4/4

Installed:
  yum-utils.noarch 0:1.1.31-46.amzn2.0.1

Dependency Installed:
  libxml2-python.x86_64 0:2.9.1-6.amzn2.4.1     python-chardet.noarch 0:2.2.1-1.amzn2     python-kitchen.noarch 0:1.1.1-5.amzn2

Complete!
: No such file or directory 5: cd: /tmp
Loaded plugins: ovl, priorities
No Match for argument
Nothing to download
/out/layer_builder.sh: line 8: dejavu-sans-fonts: command not found
/out/layer_builder.sh: line 9: dejavu-fonts-common: command not found
/out/layer_builder.sh: line 10: xorg-x11-fonts-Type1: command not found
/out/layer_builder.sh: line 11: $'\r': command not found
/out/layer_builder.sh: line 12: rpmdev-extract: command not found
/out/layer_builder.sh: line 13: $'\r': command not found
cp: cannot stat ‘/tmp/*/usr/share/fonts/*’: No such file or directory
cp: cannot stat ‘/tmp/*/usr/share/X11/fonts/*’: No such file or directory
/out/layer_builder.sh: line 17: /opt/fonts/fonts.conf: No such file or directory
/out/layer_builder.sh: line 26: $'\r': command not found
: No such file or directory 27: cd: /opt
        zip warning: name not matched: fonts/*

)ip error: Nothing to do! (try: zip -r9 /out/layer.zip . -i fonts/*
make: *** [Makefile:22: build/fonts-layer.zip] Error 12

**Comment by kalekseev** [comment]
@jjpretelta there's some problem with docker image I guess

```
bash /out/layer_builder.sh
: invalid optioner.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

...

: No such file or directory 5: cd: /tmp
```

these errors shouldn't happen, try to pull latest docker images

**Comment by kalekseev** [comment]
I got interested how that error can happen `: invalid optioner.sh: line 3: set: -`, see how `:invalid option` overwrote part of `layer_builder.sh`.
Found this answer https://stackoverflow.com/a/35352993/2767677

**Comment by jjpretelta** [comment]
> @jjpretelta there's some problem with docker image I guess
> 
> ```
> bash /out/layer_builder.sh
> : invalid optioner.sh: line 3: set: -
> set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
> 
> ...
> 
> : No such file or directory 5: cd: /tmp
> ```
> 
> these errors shouldn't happen, try to pull latest docker images

Yes, it shouldn´t but exactly where changes I have to do for that, I am not familiar with Docker

Thanks in advance
