### ISSUE TITLE
weasyprint/README.md is out of date

### ISSUE THREAD

**Issue by penguinairlines** [kotify/cloud-print-utils#26]
`make test.weasyprint` currently returns an error
`make: *** No rule to make target 'test.weasyprint'.  Stop.`

Indeed, there is no test.weasyprint in the current Makefile.

There is an old reference at https://github.com/kotify/cloud-print-utils/commit/e4bdd9552e8988278c55f957a664e5b97c0d1578

Seems like the README needs to be updated to incorporate the tests that replaced this, like test.start.container and test.print.report. 

Also, it would be helpful to list dependencies in the getting started documentation. Docker is obvious enough, but not everyone has unzip, zip, jq, etc. - and it's not fun tripping over these while trying to figure out these undocumented tests. 

Once these are installed, `make test.start.container` does start a container, but leaves the user hanging in terms of testing. No documentation comes up when searching the repository for "test.start.container".
```
docker run --rm --platform=linux/amd64 \
    -e GDK_PIXBUF_MODULE_FILE="/opt/lib/loaders.cache" \
    -e FONTCONFIG_PATH="/opt/fonts" \
    -e XDG_DATA_DIRS="/opt/lib" \
    -v `pwd`/weasyprint:/var/task \
    -v `pwd`/build/opt:/opt \
                -p 9000:8080 \
                public.ecr.aws/lambda/python:3.12 \
    lambda_function.lambda_handler
23 Aug 2024 01:24:39,326 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
```
In another shell, I can see the container is running. I can also run the 2nd test which is able to generate a document using the first test's container. 
```
$ sudo docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS          PORTS                                       NAMES
4c0487f47ec7   public.ecr.aws/lambda/python:3.12   "/lambda-entrypoint.…"   13 minutes ago   Up 13 minutes   0.0.0.0:9000->8080/tcp, :::9000->8080/tcp   keen_villani
$ make test.print.report
which jq
/usr/sbin/jq
curl --fail -s -S -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
        -d '{"return": "base64", "filename": "report.pdf", "url": "https://kotify.github.io/cloud-print-utils/samples/report/"}' \
        | tail -1 | jq .body | tr -d '"' | base64 -d > report.pdf
Check ./report.pdf, eg.: xdg-open report.pdf
```

So, clearly the tests work, just need to update the README to indicate these steps for native testing, especially since the root README says "for details and docker lambda example see related [readme](https://github.com/kotify/cloud-print-utils/blob/master/weasyprint/README.md).", so I'm expecting to find the details to build the image on this document and prepare to upload to ECR. It could also be nice for the first test to print a message to std out letting the user know what to do next.

**Comment by kalekseev** [comment]
Seems like you've done a great job investigating all the problems. If you can transform your suggestions into a PR, I'll gladly accept it.

**Comment by penguinairlines** [comment]
Sure thing. 

I tried to match the existing formatting, language, and kept the instructions brief. I'm looking forward to your feedback.

**Comment by kalekseev** [comment]
Thank you!
