### ISSUE TITLE
OSError: cannot load library 'pango-1.0-0' | Is this an arm64 issue?

### ISSUE THREAD

**Issue by Iamrodos** [kotify/cloud-print-utils#29]
Hi, I am trying to get a layer working for Weasyprint using the zip file in the releases.

I am getting an error 

` File \"/var/task/cffi/api.py\", line 829, in _load_backend_lib
    raise OSError(msg)\nOSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'"
`
I have configured the 3 environment variables as directed. I have been through all the closed issues. Have tried a lot of ways of troubleshooting without any success.

**I was wondering if it was because I am using arm64 for the lambda function. Do the zip files only work on x86?** I can't see any mention of the architecture in the docs or filenames. 

Otherwise, any hints on what might be going wrong are appreciated. 

Thanks

- Using Python 3.12, at the release file [weasyprint-layer-python3.12.zip](https://github.com/kotify/cloud-print-utils/releases/download/weasyprint-61.2/weasyprint-layer-python3.12.zip)

**Comment by kalekseev** [comment]
try x86 lambda function

**Comment by kalekseev** [comment]
release built on github actions https://github.com/kotify/cloud-print-utils/blob/master/.github/workflows/ci.yml it's x86 at the moment

**Comment by Iamrodos** [comment]
That fixed it! Be good to see a note of this in https://github.com/kotify/cloud-print-utils/tree/master/weasyprint notes.

Thanks for the great utility!

**Comment by kalekseev** [comment]
I'll accept PR with that note

**Comment by TheJuki** [comment]
PR for Arm64 build support: https://github.com/kotify/cloud-print-utils/pull/36
