### ISSUE TITLE
[ERROR] Cannot run an AWS Lambda using python3.11

### ISSUE THREAD

**Issue by RPierrick** [kotify/cloud-print-utils#31]
Hello, 

I recently installed weasyprint version 62.3 on a lambda running python 3.11 and I had a first error that took me to this GIT repo. 

By switching to python 3.12 and thanks to your help, I managed to get weasyprint to work on a lambda, but I'd like to get the lambda to work in python 3.11.

I slightly modified the repo to generate the layers in 3.11, but I end up with the following error message : 

`[ERROR] OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'`

Here are the changes I made to the **weasyprint/layer_builder.sh** file

```
#!/bin/bash
# Don't forget to set these env variables in aws lambda
# GDK_PIXBUF_MODULE_FILE="/opt/lib/loaders.cache"
# XDG_DATA_DIRS="/opt/lib"
set -e
yum install -y yum-utils rpmdevtools
cd /tmp
yumdownloader --resolve \
    cairo.x86_64 \
    gdk-pixbuf2.x86_64 \
    libffi.x86_64 \
    pango.x86_64 \
    expat.x86_64 \
    libmount.x86_64 \
    libuuid.x86_64 \
    libblkid.x86_64 \
    glib2.x86_64 \
    libthai.x86_64 \
    fribidi.x86_64 \
    harfbuzz.x86_64 \
    libdatrie.x86_64 \
    freetype.x86_64 \
    graphite2.x86_64 \
    libbrotli.x86_64 \
    libpng.x86_64 \
    fontconfig.x86_64 \

rpmdev-extract -- *rpm

mkdir /opt/lib
cp -P -r /tmp/*/usr/lib64/* /opt/lib
# pixbuf need list loaders cache
# https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-query-loaders.html
PIXBUF_BIN=$(find /tmp -name gdk-pixbuf-query-loaders-64)
GDK_PIXBUF_MODULEDIR=$(find /opt/lib/gdk-pixbuf-2.0/ -name loaders)
export GDK_PIXBUF_MODULEDIR
$PIXBUF_BIN > /opt/lib/loaders.cache
# pixbuf need mime database
# https://www.linuxtopia.org/online_books/linux_desktop_guides/gnome_2.14_admin_guide/mimetypes-database.html
cp -r /usr/share/mime /opt/lib/mime

RUNTIME=$(grep AWS_EXECUTION_ENV "$LAMBDA_RUNTIME_DIR/bootstrap" | cut -d _ -f 5)
export RUNTIME
mkdir -p "/opt/python/lib/$RUNTIME/site-packages"
python -m pip install "weasyprint" -t "/opt/python/lib/$RUNTIME/site-packages"

cd /opt
zip -r9 /out/layer.zip lib/* python/*
```

If you would like more information, please do not hesitate to contact me

**Comment by kalekseev** [comment]
lambda python 3.11 runs on amazon linux 2, you can run old versions of weasyprint on it, this project was supporting it prior to 3.12 changes made in https://github.com/kotify/cloud-print-utils/pull/20/files

**Comment by RPierrick** [comment]
Hello, but the lastest version compatible with AWS Lambda was Weasyprint<53.0, which was release +3 years ago

**Comment by kalekseev** [comment]
> Hello, but the lastest version compatible with AWS Lambda was Weasyprint<53.0, which was release +3 years ago

yes, that's why we use lambda with py3.12 runtime
