### ISSUE TITLE
Layer execution error

### ISSUE THREAD

**Issue by 3dw1np** [kotify/cloud-print-utils#4]
I made a quick try by adding the layer built on Amazon Linux Machine into an existing lambda and I have the following error:

```
START RequestId: 299688df-71a9-4a15-8fa2-d994e26d1274 Version: $LATEST
--
Fontconfig error: Cannot load default config file
/opt/python/lib/python3.8/site-packages/weasyprint/fonts.py:221: UserWarning: FontConfig cannot load default config file.Expect ugly output.
warnings.warn(
/var/task/magic.py:193: SyntaxWarning: "is" with a literal. Did you mean "=="?
if result is -1:
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': failed to find libmagic.  Check your installationTraceback (most recent call last):
END RequestId: 299688df-71a9-4a15-8fa2-d994e26d1274
````

Fontconfig and libmagic  should be in the zip file generated by make and docker isn't ?

Thanks for help !

**Comment by kalekseev** [comment]
See [environment variables section](https://github.com/kotify/cloud-print-utils/blob/master/weasyprint/README.md#lambda-layer) for font config configuration.
AFAIK libmagic is not required by weasyprint
