### ISSUE TITLE
.webp support?

### ISSUE THREAD

**Issue by colleen-mydoma** [kotify/cloud-print-utils#8]
I'm noticing that errors occur when users try to include .webp image files. 
[ERROR]	2022-06-28T16:53:45.987Z	25084a15-ae8b-486d-b05d-1ce1995629ac	Failed to load image at "https://... .webp" (Pixbuf error: Unrecognized image file format)

Any idea what I can do to resolve?

**Comment by kalekseev** [comment]
@colleen-mydoma pixbuf can't load webp image, to fix that you probably need to compile https://github.com/aruiz/webp-pixbuf-loader and add it to the lambda layer.
